version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ES_USER}
      - ELASTIC_PASSWORD=${ES_PASS}
    ports:
      - "${ES_PORT}:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  mongodb:
    image: mongo:${MONGO_VERSION}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodata:/data/db

  postgres:
    image: postgres:${PG_VERSION}
    environment:
    - POSTGRES_USER=${PG_USER}
    - POSTGRES_PASSWORD=${PG_PASS}
    - POSTGRES_DB=${PG_DB}
    - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  esdata:
  mongodata:
  pgdata:
